// Criado - Saulo Prado Versão 1.0 Junho de 2016 Versão 2.0 Março de 2026
import { LinkItem, SocialResponsibilityItem } from './types';

export const SOCIAL_RESPONSIBILITY: SocialResponsibilityItem[] = [
  { name: 'Alcoólicos Anônimos', url: 'https://www.aa.org.br/', description: 'Recuperação do alcoolismo' },
  { name: 'Doe Órgãos', url: 'https://www.gov.br/saude/pt-br/composicao/saes/snt', description: 'Doe Vida' },
  { name: 'Boldrini', url: 'https://www.boldrini.org.br/', description: 'Centro infantil' },
  { name: 'CVV', url: 'https://www.cvv.org.br/', description: 'Apoio Emocional 188' },
];

// --- FUTEBOL LISTS ---
export const FOOTBALL_BRASIL: LinkItem[] = [
  { id: 'fut_br_1', name: 'Flamengo', url: 'https://www.flamengo.com.br', category: 'Futebol' },
  { id: 'fut_br_2', name: 'Palmeiras', url: 'https://www.palmeiras.com.br', category: 'Futebol' },
  { id: 'fut_br_3', name: 'São Paulo', url: 'https://www.saopaulofc.net', category: 'Futebol' },
  { id: 'fut_br_4', name: 'Corinthians', url: 'https://www.corinthians.com.br', category: 'Futebol' },
  { id: 'fut_br_5', name: 'Atlético-MG', url: 'https://atletico.com.br', category: 'Futebol' },
  { id: 'fut_br_6', name: 'Fluminense', url: 'https://www.fluminense.com.br', category: 'Futebol' },
  { id: 'fut_br_7', name: 'Grêmio', url: 'https://gremio.net', category: 'Futebol' },
  { id: 'fut_br_8', name: 'Internacional', url: 'https://internacional.com.br', category: 'Futebol' },
  { id: 'fut_br_9', name: 'Botafogo', url: 'https://www.botafogo.com.br', category: 'Futebol' },
  { id: 'fut_br_10', name: 'Vasco', url: 'https://vasco.com.br', category: 'Futebol' },
  { id: 'fut_br_11', name: 'Cruzeiro', url: 'https://www.cruzeiro.com.br', category: 'Futebol' },
  { id: 'fut_br_12', name: 'Bahia', url: 'https://www.esporteclubebahia.com.br', category: 'Futebol' },
  { id: 'fut_br_13', name: 'Athletico-PR', url: 'https://www.athletico.com.br', category: 'Futebol' },
  { id: 'fut_br_14', name: 'Santos', url: 'https://www.santosfc.com.br', category: 'Futebol' },
  { id: 'fut_br_15', name: 'Bragantino', url: 'https://www.redbullbragantino.com.br', category: 'Futebol' },
  { id: 'fut_br_16', name: 'Vitória', url: 'https://www.ecvitoria.com.br', category: 'Futebol' },
  { id: 'fut_br_17', name: 'Mirassol', url: 'https://www.mirassolfc.com.br', category: 'Futebol' },
  { id: 'fut_br_18', name: 'Coritiba', url: 'https://www.coritiba.com.br', category: 'Futebol' },
  { id: 'fut_br_19', name: 'Chapecoense', url: 'https://chapecoense.com', category: 'Futebol' },
  { id: 'fut_br_20', name: 'Remo', url: 'https://clubedoremo.com.br', category: 'Futebol' },
];

export const FOOTBALL_EUROPE: LinkItem[] = [
  { id: 'fut_eu_1', name: 'Real Madrid', url: 'https://www.realmadrid.com', category: 'Futebol' },
  { id: 'fut_eu_2', name: 'Barcelona', url: 'https://www.fcbarcelona.com', category: 'Futebol' },
  { id: 'fut_eu_3', name: 'Liverpool', url: 'https://www.liverpoolfc.com', category: 'Futebol' },
  { id: 'fut_eu_4', name: 'Bayern', url: 'https://fcbayern.com', category: 'Futebol' },
  { id: 'fut_eu_5', name: 'PSG', url: 'https://www.psg.fr', category: 'Futebol' },
  { id: 'fut_eu_6', name: 'Arsenal', url: 'https://www.arsenal.com', category: 'Futebol' },
  { id: 'fut_eu_7', name: 'Man. City', url: 'https://www.mancity.com', category: 'Futebol' },
  { id: 'fut_eu_8', name: 'Atl. Madrid', url: 'https://en.atleticodemadrid.com', category: 'Futebol' },
  { id: 'fut_eu_9', name: 'Chelsea', url: 'https://www.chelseafc.com', category: 'Futebol' },
  { id: 'fut_eu_10', name: 'Tottenham', url: 'https://www.tottenhamhotspur.com', category: 'Futebol' },
  { id: 'fut_eu_11', name: 'Newcastle', url: 'https://www.newcastleunited.com', category: 'Futebol' },
  { id: 'fut_eu_12', name: 'B. Leverkusen', url: 'https://www.bayer04.de', category: 'Futebol' },
  { id: 'fut_eu_13', name: 'Sporting', url: 'https://www.sporting.pt', category: 'Futebol' },
  { id: 'fut_eu_14', name: 'Galatasaray', url: 'https://www.galatasaray.org', category: 'Futebol' },
  { id: 'fut_eu_15', name: 'Atalanta', url: 'https://www.atalanta.it', category: 'Futebol' },
  { id: 'fut_eu_16', name: 'Bodø/Glimt', url: 'https://www.glimt.no', category: 'Futebol' },
];

export const FOOTBALL_FIFA: LinkItem[] = [
  { id: 'fut_fifa_1', name: 'Brasil (CBF)', url: 'https://www.cbf.com.br', category: 'Futebol' },
  { id: 'fut_fifa_2', name: 'Argentina (AFA)', url: 'https://www.afa.com.ar', category: 'Futebol' },
  { id: 'fut_fifa_3', name: 'França (FFF)', url: 'https://www.fff.fr', category: 'Futebol' },
  { id: 'fut_fifa_4', name: 'Bélgica', url: 'https://www.rbfa.be', category: 'Futebol' },
  { id: 'fut_fifa_5', name: 'Inglaterra', url: 'https://www.englandfootball.com', category: 'Futebol' },
  { id: 'fut_fifa_6', name: 'Portugal', url: 'https://www.fpf.pt', category: 'Futebol' },
  { id: 'fut_fifa_7', name: 'Holanda', url: 'https://www.onsoranje.nl', category: 'Futebol' },
  { id: 'fut_fifa_8', name: 'Espanha', url: 'https://rfef.es', category: 'Futebol' },
  { id: 'fut_fifa_9', name: 'Itália', url: 'https://www.figc.it', category: 'Futebol' },
  { id: 'fut_fifa_10', name: 'Croácia', url: 'https://hns-cff.hr', category: 'Futebol' },
  { id: 'fut_fifa_11', name: 'EUA', url: 'https://www.ussoccer.com', category: 'Futebol' },
  { id: 'fut_fifa_12', name: 'Alemanha', url: 'https://www.dfb.de', category: 'Futebol' },
  { id: 'fut_fifa_13', name: 'Uruguai', url: 'https://www.auf.org.uy', category: 'Futebol' },
  { id: 'fut_fifa_14', name: 'Japão', url: 'https://www.jfa.jp', category: 'Futebol' },
];

// --- JORNAIS / COMUNICAÇÃO LISTS ---
export const NEWSPAPERS_BY_STATE: Record<string, LinkItem[]> = {
  'Acre (AC)': [{ id: 'j_ac_1', name: 'A Gazeta do Acre', url: 'https://agazetadoacre.com', category: 'Comunicação' }],
  'Alagoas (AL)': [{ id: 'j_al_1', name: 'Gazeta de Alagoas', url: 'https://www.gazetadealagoas.com.br', category: 'Comunicação' }],
  'Amapá (AP)': [{ id: 'j_ap_1', name: 'Diário do Amapá', url: 'https://www.diariodoamapa.com.br', category: 'Comunicação' }],
  'Amazonas (AM)': [{ id: 'j_am_1', name: 'A Crítica', url: 'https://www.acritica.com', category: 'Comunicação' }],
  'Bahia (BA)': [{ id: 'j_ba_1', name: 'A Tarde', url: 'https://atarde.com.br', category: 'Comunicação' }],
  'Ceará (CE)': [{ id: 'j_ce_1', name: 'O Povo', url: 'https://www.opovo.com.br', category: 'Comunicação' }],
  'Distrito Federal (DF)': [{ id: 'j_df_1', name: 'Correio Braziliense', url: 'https://www.correiobraziliense.com.br', category: 'Comunicação' }],
  'Espírito Santo (ES)': [{ id: 'j_es_1', name: 'A Gazeta', url: 'https://www.agazeta.com.br', category: 'Comunicação' }],
  'Goiás (GO)': [{ id: 'j_go_1', name: 'O Popular', url: 'https://opopular.com.br', category: 'Comunicação' }],
  'Maranhão (MA)': [{ id: 'j_ma_1', name: 'O Imparcial', url: 'https://oimparcial.com.br', category: 'Comunicação' }],
  'Mato Grosso (MT)': [{ id: 'j_mt_1', name: 'Diário de Cuiabá', url: 'https://www.diariodecuiaba.com.br', category: 'Comunicação' }],
  'Mato Grosso do Sul (MS)': [{ id: 'j_ms_1', name: 'Correio do Estado', url: 'https://correiodoestado.com.br', category: 'Comunicação' }],
  'Minas Gerais (MG)': [{ id: 'j_mg_1', name: 'Estado de Minas', url: 'https://www.em.com.br', category: 'Comunicação' }],
  'Pará (PA)': [{ id: 'j_pa_1', name: 'O Liberal', url: 'https://www.oliberal.com', category: 'Comunicação' }],
  'Paraíba (PB)': [{ id: 'j_pb_1', name: 'Jornal da Paraíba', url: 'https://jornaldaparaiba.com.br', category: 'Comunicação' }],
  'Paraná (PR)': [{ id: 'j_pr_1', name: 'Gazeta do Povo', url: 'https://www.gazetadopovo.com.br', category: 'Comunicação' }],
  'Pernambuco (PE)': [{ id: 'j_pe_1', name: 'Jornal do Commercio', url: 'https://jc.ne10.uol.com.br', category: 'Comunicação' }],
  'Piauí (PI)': [{ id: 'j_pi_1', name: 'Cidade Verde', url: 'https://cidadeverde.com', category: 'Comunicação' }],
  'Rio de Janeiro (RJ)': [{ id: 'j_rj_1', name: 'O Globo', url: 'https://oglobo.globo.com', category: 'Comunicação' }],
  'Rio Grande do Norte (RN)': [{ id: 'j_rn_1', name: 'Tribuna do Norte', url: 'https://tribunadonorte.com.br', category: 'Comunicação' }],
  'Rio Grande do Sul (RS)': [{ id: 'j_rs_1', name: 'Zero Hora (GZH)', url: 'https://gzh.rs', category: 'Comunicação' }],
  'Rondônia (RO)': [{ id: 'j_ro_1', name: 'Diário da Amazônia', url: 'https://www.diariodaamazonia.com.br', category: 'Comunicação' }],
  'Roraima (RR)': [{ id: 'j_rr_1', name: 'Folha de Boa Vista', url: 'https://folhabv.com.br', category: 'Comunicação' }],
  'Santa Catarina (SC)': [{ id: 'j_sc_1', name: 'NSC Total', url: 'https://www.nsctotal.com.br', category: 'Comunicação' }],
  'São Paulo (SP)': [{ id: 'j_sp_1', name: 'Folha de S.Paulo', url: 'https://www.folha.uol.com.br', category: 'Comunicação' }],
  'Sergipe (SE)': [{ id: 'j_se_1', name: 'Jornal da Cidade', url: 'https://jornaldacidade.net', category: 'Comunicação' }],
  'Tocantins (TO)': [{ id: 'j_to_1', name: 'Jornal do Tocantins', url: 'https://www.jornaldotocantins.com.br', category: 'Comunicação' }],
};

export const NEWSPAPERS_WORLD: LinkItem[] = [
  { id: 'j_w_1', name: 'The New York Times', url: 'https://www.nytimes.com', category: 'Comunicação' },
  { id: 'j_w_2', name: 'The Washington Post', url: 'https://www.washingtonpost.com', category: 'Comunicação' },
  { id: 'j_w_3', name: 'The Wall Street Journal', url: 'https://www.wsj.com', category: 'Comunicação' },
  { id: 'j_w_4', name: 'The Guardian', url: 'https://www.theguardian.com', category: 'Comunicação' },
  { id: 'j_w_5', name: 'BBC News', url: 'https://www.bbc.com/news', category: 'Comunicação' },
  { id: 'j_w_6', name: 'Financial Times', url: 'https://www.ft.com', category: 'Comunicação' },
  { id: 'j_w_7', name: 'Le Monde', url: 'https://www.lemonde.fr', category: 'Comunicação' },
  { id: 'j_w_8', name: 'Le Figaro', url: 'https://www.lefigaro.fr', category: 'Comunicação' },
  { id: 'j_w_9', name: 'El País', url: 'https://elpais.com', category: 'Comunicação' },
  { id: 'j_w_10', name: 'El Mundo', url: 'https://www.elmundo.es', category: 'Comunicação' },
  { id: 'j_w_11', name: 'Corriere della Sera', url: 'https://www.corriere.it', category: 'Comunicação' },
  { id: 'j_w_12', name: 'Der Spiegel', url: 'https://www.spiegel.de', category: 'Comunicação' },
  { id: 'j_w_13', name: 'Público (Portugal)', url: 'https://www.publico.pt', category: 'Comunicação' },
  { id: 'j_w_14', name: 'Clarín', url: 'https://www.clarin.com', category: 'Comunicação' },
  { id: 'j_w_15', name: 'La Nación', url: 'https://www.lanacion.com.ar', category: 'Comunicação' },
  { id: 'j_w_16', name: 'El Tiempo', url: 'https://www.eltiempo.com', category: 'Comunicação' },
  { id: 'j_w_17', name: 'Asahi Shimbun', url: 'https://www.asahi.com', category: 'Comunicação' },
  { id: 'j_w_18', name: 'The Hindu', url: 'https://www.thehindu.com', category: 'Comunicação' },
  { id: 'j_w_19', name: 'South China Morning Post', url: 'https://www.scmp.com', category: 'Comunicação' },
  { id: 'j_w_20', name: 'Al Jazeera', url: 'https://www.aljazeera.com', category: 'Comunicação' },
];

export const GAME_ITEMS: LinkItem[] = [
  { id: 'g1', name: 'Roblox', url: 'https://www.roblox.com', category: 'Games' },
  { id: 'g2', name: 'Twitch', url: 'https://www.twitch.tv', category: 'Games' },
  { id: 'g3', name: 'Steam', url: 'https://store.steampowered.com', category: 'Games' },
  { id: 'g4', name: 'Discord', url: 'https://discord.com', category: 'Games' },
  { id: 'g5', name: 'Epic Games', url: 'https://store.epicgames.com', category: 'Games' },
  { id: 'g6', name: 'Chess.com', url: 'https://www.chess.com', category: 'Games' },
  { id: 'g7', name: 'PlayStation', url: 'https://www.playstation.com', category: 'Games' },
  { id: 'g8', name: 'Xbox Cloud', url: 'https://www.xbox.com/play', category: 'Games' },
  { id: 'g9', name: 'Gartic', url: 'https://gartic.com.br', category: 'Games' },
  { id: 'g10', name: 'Poki', url: 'https://poki.com/br', category: 'Games' },
  { id: 'g11', name: 'IGN Brasil', url: 'https://br.ign.com', category: 'Games' },
  { id: 'g12', name: 'The Enemy', url: 'https://www.theenemy.com.br', category: 'Games' },
  { id: 'g13', name: 'Nintendo', url: 'https://www.nintendo.com/pt-br/', category: 'Games' },
  { id: 'g14', name: 'Ubisoft', url: 'https://www.ubisoft.com/pt-br/', category: 'Games' },
  { id: 'g15', name: 'EA Games', url: 'https://www.ea.com/pt-br', category: 'Games' },
  // Mais 5 sites adicionados
  { id: 'g16', name: 'Nuuvem', url: 'https://www.nuuvem.com', category: 'Games' },
  { id: 'g17', name: 'Riot Games', url: 'https://www.riotgames.com', category: 'Games' },
  { id: 'g18', name: 'Battle.net', url: 'https://shop.battle.net', category: 'Games' },
  { id: 'g19', name: 'GOG.com', url: 'https://www.gog.com', category: 'Games' },
  { id: 'g20', name: 'Itch.io', url: 'https://itch.io', category: 'Games' },
];

export const INDICATOR_ITEMS: LinkItem[] = [
  { id: 'i1', name: 'Google Trends', url: 'https://trends.google.com.br', category: 'Indicadores' },
  { id: 'i2', name: 'TradingView', url: 'https://br.tradingview.com', category: 'Indicadores' },
  { id: 'i3', name: 'InfoMoney', url: 'https://www.infomoney.com.br/cotacoes/', category: 'Indicadores' },
  { id: 'i4', name: 'Climatempo', url: 'https://www.climatempo.com.br', category: 'Indicadores' },
  { id: 'i5', name: 'Speedtest', url: 'https://www.speedtest.net/pt', category: 'Indicadores' },
  { id: 'i6', name: 'CoinMarketCap', url: 'https://coinmarketcap.com/pt-br/', category: 'Indicadores' },
  { id: 'i7', name: 'Investing.com', url: 'https://br.investing.com', category: 'Indicadores' },
  { id: 'i8', name: 'IBGE', url: 'https://www.ibge.gov.br', category: 'Indicadores' },
  { id: 'i9', name: 'FlightRadar24', url: 'https://www.flightradar24.com', category: 'Indicadores' },
  { id: 'i10', name: 'Waze Live Map', url: 'https://www.waze.com/live-map', category: 'Indicadores' },
  { id: 'i11', name: 'Banco Central', url: 'https://www.bcb.gov.br', category: 'Indicadores' },
  { id: 'i12', name: 'IPEA', url: 'https://www.ipea.gov.br', category: 'Indicadores' },
  // Novos indicadores
  { id: 'i13', name: 'Status Invest', url: 'https://statusinvest.com.br', category: 'Indicadores' },
  { id: 'i14', name: 'Investidor10', url: 'https://investidor10.com.br', category: 'Indicadores' },
  { id: 'i15', name: 'SimilarWeb', url: 'https://www.similarweb.com', category: 'Indicadores' },
  { id: 'i16', name: 'Trading Economics', url: 'https://pt.tradingeconomics.com', category: 'Indicadores' },
  { id: 'i17', name: 'B3 (Bolsa)', url: 'https://www.b3.com.br', category: 'Indicadores' },
];

export const AI_LLM_ITEMS: LinkItem[] = [
  { id: 'ai_1', name: 'ChatGPT', url: 'https://chat.openai.com', category: 'IA' },
  { id: 'ai_2', name: 'Google Gemini', url: 'https://gemini.google.com', category: 'IA' },
  { id: 'ai_3', name: 'Claude', url: 'https://claude.ai', category: 'IA' },
  { id: 'ai_4', name: 'Perplexity', url: 'https://www.perplexity.ai', category: 'IA' },
  { id: 'ai_5', name: 'Grok', url: 'https://grok.com', category: 'IA' },
  { id: 'ai_6', name: 'Mistral Le Chat', url: 'https://chat.mistral.ai', category: 'IA' },
  { id: 'ai_7', name: 'Meta AI', url: 'https://www.meta.ai', category: 'IA' },
  { id: 'ai_8', name: 'Pi AI', url: 'https://pi.ai', category: 'IA' },
  { id: 'ai_9', name: 'Poe', url: 'https://poe.com', category: 'IA' },
  { id: 'ai_10', name: 'You.com', url: 'https://you.com', category: 'IA' },
  { id: 'ai_11', name: 'Microsoft Copilot', url: 'https://copilot.microsoft.com', category: 'IA' },
  { id: 'ai_12', name: 'GitHub Copilot', url: 'https://github.com/features/copilot', category: 'IA' },
  { id: 'ai_13', name: 'Character.AI', url: 'https://character.ai', category: 'IA' },
  { id: 'ai_14', name: 'Phind', url: 'https://www.phind.com', category: 'IA' },
  { id: 'ai_15', name: 'Cursor', url: 'https://www.cursor.com', category: 'IA' },
  { id: 'ai_16', name: 'Midjourney', url: 'https://www.midjourney.com', category: 'IA' },
  { id: 'ai_17', name: 'Leonardo AI', url: 'https://leonardo.ai', category: 'IA' },
  { id: 'ai_18', name: 'Runway', url: 'https://runwayml.com', category: 'IA' },
  { id: 'ai_19', name: 'ElevenLabs', url: 'https://elevenlabs.io', category: 'IA' },
  { id: 'ai_20', name: 'Hugging Face', url: 'https://huggingface.co', category: 'IA' },
];

export const AI_CHINA_ITEMS: LinkItem[] = [
  { id: 'ai_cn_1', name: 'DeepSeek', url: 'https://chat.deepseek.com', category: 'IA' },
  { id: 'ai_cn_2', name: 'Kimi', url: 'https://kimi.moonshot.cn', category: 'IA' },
  { id: 'ai_cn_3', name: 'Qwen Chat', url: 'https://chat.qwen.ai', category: 'IA' },
  { id: 'ai_cn_4', name: 'Doubao', url: 'https://www.doubao.com', category: 'IA' },
  { id: 'ai_cn_5', name: 'Yuanbao', url: 'https://yuanbao.tencent.com', category: 'IA' },
  { id: 'ai_cn_6', name: 'ERNIE Bot (Yiyan)', url: 'https://yiyan.baidu.com', category: 'IA' },
  { id: 'ai_cn_7', name: 'Hunyuan', url: 'https://hunyuan.tencent.com', category: 'IA' },
  { id: 'ai_cn_8', name: 'Zhipu Qingyan', url: 'https://chatglm.cn', category: 'IA' },
  { id: 'ai_cn_9', name: 'MiniMax', url: 'https://www.minimax.io', category: 'IA' },
  { id: 'ai_cn_10', name: 'Manus', url: 'https://manus.im', category: 'IA' },
];

export const PRODUCTIVITY_ITEMS: LinkItem[] = [
  { id: 'prod_1', name: 'Notion', url: 'https://www.notion.so', category: 'Produtividade' },
  { id: 'prod_2', name: 'Trello', url: 'https://trello.com', category: 'Produtividade' },
  { id: 'prod_3', name: 'Asana', url: 'https://asana.com', category: 'Produtividade' },
  { id: 'prod_4', name: 'ClickUp', url: 'https://clickup.com', category: 'Produtividade' },
  { id: 'prod_5', name: 'Monday.com', url: 'https://monday.com', category: 'Produtividade' },
  { id: 'prod_6', name: 'Slack', url: 'https://slack.com', category: 'Produtividade' },
  { id: 'prod_7', name: 'Microsoft Teams', url: 'https://www.microsoft.com/microsoft-teams', category: 'Produtividade' },
  { id: 'prod_8', name: 'Google Workspace', url: 'https://workspace.google.com', category: 'Produtividade' },
  { id: 'prod_9', name: 'Canva', url: 'https://www.canva.com', category: 'Produtividade' },
  { id: 'prod_10', name: 'Figma', url: 'https://www.figma.com', category: 'Produtividade' },
  { id: 'prod_11', name: 'Miro', url: 'https://miro.com', category: 'Produtividade' },
  { id: 'prod_12', name: 'WeTransfer', url: 'https://wetransfer.com', category: 'Produtividade' },
  { id: 'prod_13', name: 'Zoom', url: 'https://zoom.us', category: 'Produtividade' },
  { id: 'prod_14', name: 'Calendly', url: 'https://calendly.com', category: 'Produtividade' },
];

export const DEV_CORE_ITEMS: LinkItem[] = [
  { id: 'dev_1', name: 'Python Docs', url: 'https://docs.python.org/3/', category: 'Dev' },
  { id: 'dev_2', name: 'Pandas', url: 'https://pandas.pydata.org', category: 'Dev' },
  { id: 'dev_3', name: 'NumPy', url: 'https://numpy.org', category: 'Dev' },
  { id: 'dev_4', name: 'Matplotlib', url: 'https://matplotlib.org', category: 'Dev' },
  { id: 'dev_5', name: 'Scikit-learn', url: 'https://scikit-learn.org', category: 'Dev' },
  { id: 'dev_6', name: 'Jupyter', url: 'https://jupyter.org', category: 'Dev' },
  { id: 'dev_7', name: 'JavaScript (MDN)', url: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript', category: 'Dev' },
  { id: 'dev_8', name: 'TypeScript', url: 'https://www.typescriptlang.org/docs/', category: 'Dev' },
  { id: 'dev_9', name: 'Node.js', url: 'https://nodejs.org/en/docs', category: 'Dev' },
  { id: 'dev_10', name: 'React', url: 'https://react.dev', category: 'Dev' },
  { id: 'dev_11', name: 'Next.js', url: 'https://nextjs.org/docs', category: 'Dev' },
  { id: 'dev_12', name: 'Vue.js', url: 'https://vuejs.org', category: 'Dev' },
  { id: 'dev_13', name: 'Angular', url: 'https://angular.dev', category: 'Dev' },
  { id: 'dev_14', name: 'SQLBolt', url: 'https://sqlbolt.com', category: 'Dev' },
  { id: 'dev_15', name: 'PostgreSQL', url: 'https://www.postgresql.org/docs/', category: 'Dev' },
  { id: 'dev_16', name: 'MySQL', url: 'https://dev.mysql.com/doc/', category: 'Dev' },
  { id: 'dev_17', name: 'MongoDB', url: 'https://www.mongodb.com/docs/', category: 'Dev' },
  { id: 'dev_18', name: 'Django', url: 'https://docs.djangoproject.com', category: 'Dev' },
  { id: 'dev_19', name: 'FastAPI', url: 'https://fastapi.tiangolo.com', category: 'Dev' },
  { id: 'dev_20', name: 'GitHub', url: 'https://github.com', category: 'Dev' },
];

export const DEV_README_ITEMS: LinkItem[] = [
  { id: 'dev_rd_1', name: 'readme.so', url: 'https://readme.so', category: 'Dev' },
  { id: 'dev_rd_2', name: 'Make a README', url: 'https://www.makeareadme.com', category: 'Dev' },
  { id: 'dev_rd_3', name: 'Shields.io', url: 'https://shields.io', category: 'Dev' },
  { id: 'dev_rd_4', name: 'Carbon', url: 'https://carbon.now.sh', category: 'Dev' },
  { id: 'dev_rd_5', name: 'GitHub Gist', url: 'https://gist.github.com', category: 'Dev' },
  { id: 'dev_rd_6', name: 'Mermaid Live', url: 'https://mermaid.live', category: 'Dev' },
];

export const HOME_ITEMS: LinkItem[] = [
  // IA, Produtividade e Dev
  { id: '1', name: 'ChatGPT', url: 'https://chat.openai.com', category: 'IA' },
  { id: '2', name: 'Google Gemini', url: 'https://gemini.google.com', category: 'IA' },
  { id: '3', name: 'Claude', url: 'https://claude.ai', category: 'IA' },
  { id: '4', name: 'Canva', url: 'https://www.canva.com', category: 'Produtividade' },
  { id: '5', name: 'Notion', url: 'https://www.notion.so', category: 'Produtividade' },
  { id: '6', name: 'Trello', url: 'https://trello.com', category: 'Produtividade' },
  { id: '7', name: 'GitHub', url: 'https://github.com', category: 'Dev' },
  { id: '8', name: 'Figma', url: 'https://www.figma.com', category: 'Produtividade' },
  { id: '9', name: 'WeTransfer', url: 'https://wetransfer.com', category: 'Produtividade' },
  { id: '10', name: 'Zoom', url: 'https://zoom.us', category: 'Produtividade' },

  // Redes Sociais
  { id: '11', name: 'WhatsApp Web', url: 'https://web.whatsapp.com', category: 'Redes Sociais' },
  { id: '12', name: 'Instagram', url: 'https://www.instagram.com', category: 'Redes Sociais' },
  { id: '13', name: 'TikTok', url: 'https://www.tiktok.com', category: 'Redes Sociais' },
  { id: '14', name: 'Facebook', url: 'https://www.facebook.com', category: 'Redes Sociais' },
  { id: '15', name: 'X (Twitter)', url: 'https://twitter.com', category: 'Redes Sociais' },
  { id: '16', name: 'LinkedIn', url: 'https://www.linkedin.com', category: 'Redes Sociais' },
  { id: '17', name: 'Pinterest', url: 'https://www.pinterest.com', category: 'Redes Sociais' },
  { id: '18', name: 'Reddit', url: 'https://www.reddit.com', category: 'Redes Sociais' },
  { id: '19', name: 'Telegram Web', url: 'https://web.telegram.org', category: 'Redes Sociais' },
  { id: '20', name: 'Threads', url: 'https://www.threads.net', category: 'Redes Sociais' },

  // Shopping & Varejo
  { id: '21', name: 'Mercado Livre', url: 'https://www.mercadolivre.com.br', category: 'Shopping & Varejo' },
  { id: '22', name: 'Amazon', url: 'https://www.amazon.com.br', category: 'Shopping & Varejo' },
  { id: '23', name: 'Shopee', url: 'https://shopee.com.br', category: 'Shopping & Varejo' },
  { id: '24', name: 'AliExpress', url: 'https://pt.aliexpress.com', category: 'Shopping & Varejo' },
  { id: '25', name: 'Magalu', url: 'https://www.magazineluiza.com.br', category: 'Shopping & Varejo' },
  { id: '26', name: 'Shein', url: 'https://br.shein.com', category: 'Shopping & Varejo' },
  { id: '27', name: 'OLX', url: 'https://www.olx.com.br', category: 'Shopping & Varejo' },
  { id: '28', name: 'Samsung', url: 'https://www.samsung.com/br', category: 'Shopping & Varejo' },
  { id: '29', name: 'Casas Bahia', url: 'https://www.casasbahia.com.br', category: 'Shopping & Varejo' },
  { id: '30', name: 'Apple', url: 'https://www.apple.com/br', category: 'Shopping & Varejo' },

  // Streaming & Vídeo (Atualizado com TVs)
  { id: '31', name: 'YouTube', url: 'https://www.youtube.com', category: 'Streaming & Vídeo' },
  { id: '32', name: 'Netflix', url: 'https://www.netflix.com', category: 'Streaming & Vídeo' },
  { id: '33', name: 'Prime Video', url: 'https://www.primevideo.com', category: 'Streaming & Vídeo' },
  { id: '34', name: 'Disney+', url: 'https://www.disneyplus.com', category: 'Streaming & Vídeo' },
  { id: '35', name: 'Globoplay', url: 'https://globoplay.globo.com', category: 'Streaming & Vídeo' },
  { id: 'tv_1', name: 'SBT Vídeos', url: 'https://www.sbt.com.br', category: 'Streaming & Vídeo' },
  { id: 'tv_2', name: 'Band', url: 'https://www.band.uol.com.br', category: 'Streaming & Vídeo' },
  { id: 'tv_3', name: 'Record TV', url: 'https://recordtv.r7.com', category: 'Streaming & Vídeo' },
  { id: 'tv_4', name: 'RedeTV!', url: 'https://www.redetv.uol.com.br', category: 'Streaming & Vídeo' },
  { id: 'tv_5', name: 'TV Cultura', url: 'https://cultura.uol.com.br', category: 'Streaming & Vídeo' },
  { id: 'tv_6', name: 'TV Gazeta', url: 'https://www.tvgazeta.com.br', category: 'Streaming & Vídeo' },
  { id: '36', name: 'Spotify', url: 'https://open.spotify.com', category: 'Streaming & Vídeo' },

  // Notícias & Portais
  { id: '41', name: 'Globo.com', url: 'https://www.globo.com', category: 'Notícias & Portais' },
  { id: '42', name: 'UOL', url: 'https://www.uol.com.br', category: 'Notícias & Portais' },
  { id: '43', name: 'G1', url: 'https://g1.globo.com', category: 'Notícias & Portais' },
  { id: '44', name: 'CNN Brasil', url: 'https://www.cnnbrasil.com.br', category: 'Notícias & Portais' },
  { id: '45', name: 'Terra', url: 'https://www.terra.com.br', category: 'Notícias & Portais' },
  { id: '46', name: 'R7', url: 'https://www.r7.com', category: 'Notícias & Portais' },
  { id: '47', name: 'Estadão', url: 'https://www.estadao.com.br', category: 'Notícias & Portais' },
  { id: '48', name: 'Folha de SP', url: 'https://www.folha.uol.com.br', category: 'Notícias & Portais' },
  { id: '49', name: 'Metrópoles', url: 'https://www.metropoles.com', category: 'Notícias & Portais' },
  { id: '50', name: 'BBC News', url: 'https://www.bbc.com/portuguese', category: 'Notícias & Portais' },

  // Bancos & Finanças
  { id: '51', name: 'Nubank', url: 'https://nubank.com.br', category: 'Bancos & Finanças' },
  { id: '52', name: 'Itaú', url: 'https://www.itau.com.br', category: 'Bancos & Finanças' },
  { id: '53', name: 'Bradesco', url: 'https://www.bradesco.com.br', category: 'Bancos & Finanças' },
  { id: '54', name: 'Caixa', url: 'https://www.caixa.gov.br', category: 'Bancos & Finanças' },
  { id: '55', name: 'Banco do Brasil', url: 'https://www.bb.com.br', category: 'Bancos & Finanças' },
  { id: '56', name: 'Santander', url: 'https://www.santander.com.br', category: 'Bancos & Finanças' },
  { id: '57', name: 'Inter', url: 'https://www.bancointer.com.br', category: 'Bancos & Finanças' },
  { id: '58', name: 'XP Invest.', url: 'https://www.xpi.com.br', category: 'Bancos & Finanças' },
  { id: '59', name: 'BTG Pactual', url: 'https://www.btgpactual.com', category: 'Bancos & Finanças' },
  { id: '60', name: 'PayPal', url: 'https://www.paypal.com', category: 'Bancos & Finanças' },

  // Governo & Serviços
  { id: '61', name: 'Gov.br', url: 'https://www.gov.br', category: 'Governo & Serviços' },
  { id: '62', name: 'Meu INSS', url: 'https://meu.inss.gov.br', category: 'Governo & Serviços' },
  { id: '63', name: 'Receita Federal', url: 'https://www.gov.br/receitafederal', category: 'Governo & Serviços' },
  { id: '64', name: 'Correios', url: 'https://www.correios.com.br', category: 'Governo & Serviços' },
  { id: '65', name: 'Detran SP', url: 'https://www.detran.sp.gov.br', category: 'Governo & Serviços' },
  { id: '66', name: 'Poupatempo', url: 'https://www.poupatempo.sp.gov.br', category: 'Governo & Serviços' },
  { id: '67', name: 'Google Maps', url: 'https://maps.google.com', category: 'Governo & Serviços' },
  { id: '68', name: 'Uber (Login)', url: 'https://m.uber.com', category: 'Governo & Serviços' },
  { id: '69', name: 'Booking.com', url: 'https://www.booking.com', category: 'Governo & Serviços' },
  { id: '70', name: 'Airbnb', url: 'https://www.airbnb.com.br', category: 'Governo & Serviços' },

  // Educação & Trabalho
  { id: '71', name: 'Udemy', url: 'https://www.udemy.com', category: 'Educação & Trabalho' },
  { id: '72', name: 'Coursera', url: 'https://www.coursera.org', category: 'Educação & Trabalho' },
  { id: '73', name: 'Duolingo', url: 'https://www.duolingo.com', category: 'Educação & Trabalho' },
  { id: '74', name: 'Wikipedia', url: 'https://pt.wikipedia.org', category: 'Educação & Trabalho' },
  { id: '75', name: 'CNPq', url: 'https://www.gov.br/cnpq', category: 'Educação & Trabalho' },
  { id: '76', name: 'Glassdoor', url: 'https://www.glassdoor.com.br', category: 'Educação & Trabalho' },
  { id: '77', name: 'Vagas.com', url: 'https://www.vagas.com.br', category: 'Educação & Trabalho' },
  { id: '78', name: 'Stack Overflow', url: 'https://stackoverflow.com', category: 'Educação & Trabalho' },
  { id: '79', name: 'Google Tradutor', url: 'https://translate.google.com', category: 'Educação & Trabalho' },
  { id: '80', name: 'Brainly', url: 'https://brainly.com.br', category: 'Educação & Trabalho' },

  // Ferramentas & Outros
  { id: '81', name: 'Speedtest', url: 'https://www.speedtest.net', category: 'Ferramentas' },
  { id: '82', name: 'Remove.bg', url: 'https://www.remove.bg', category: 'Ferramentas' },
  { id: '83', name: 'TinyURL', url: 'https://tinyurl.com', category: 'Ferramentas' },
  { id: '84', name: 'PDF iLove', url: 'https://www.ilovepdf.com/pt', category: 'Ferramentas' },
  { id: '85', name: 'Photopea', url: 'https://www.photopea.com', category: 'Ferramentas' },
  { id: '86', name: '123Apps', url: 'https://123apps.com/pt/', category: 'Ferramentas' },
  { id: '87', name: 'Google Drive', url: 'https://drive.google.com', category: 'Ferramentas' },
  { id: '88', name: 'Dropbox', url: 'https://www.dropbox.com', category: 'Ferramentas' },
  { id: '89', name: 'OneDrive', url: 'https://onedrive.live.com', category: 'Ferramentas' },
  { id: '90', name: 'Pexels', url: 'https://www.pexels.com', category: 'Ferramentas' },
  // Mais variados para fechar 100
  { id: '91', name: 'Elo7', url: 'https://www.elo7.com.br', category: 'Shopping & Varejo' },
  { id: '92', name: 'Enjoei', url: 'https://www.enjoei.com.br', category: 'Shopping & Varejo' },
  { id: '93', name: 'Buscapé', url: 'https://www.buscape.com.br', category: 'Shopping & Varejo' },
  { id: '94', name: 'Zoom Preços', url: 'https://www.zoom.com.br', category: 'Shopping & Varejo' },
  { id: '95', name: 'Decolar', url: 'https://www.decolar.com', category: 'Governo & Serviços' },
  { id: '96', name: '99 App', url: 'https://99app.com', category: 'Governo & Serviços' },
  { id: '97', name: 'Wix', url: 'https://pt.wix.com', category: 'Produtividade' },
  { id: '98', name: 'WordPress', url: 'https://br.wordpress.com', category: 'Produtividade' },
  { id: '99', name: 'HostGator', url: 'https://www.hostgator.com.br', category: 'Produtividade' },
  { id: '100', name: 'GoDaddy', url: 'https://www.godaddy.com/pt-br', category: 'Produtividade' },
];
